version: "3.7"
services:

  app:
    build:
      args:
        user: OSCAR
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: carrot
    container_name: carrot-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - carrot

  db:
    image: mysql:5.7
    ports:
    - "3306:3306"
    container_name: carrot-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_ROOT_HOST: '%'
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
    networks:
      - carrot

  nginx:
    image: nginx:alpine
    container_name: carrot-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - carrot

networks:
  carrot:
    driver: bridge
